/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsInt,
  Min,
  Max,
  IsOptional,
  IsDate,
  IsString,
  IsBoolean,
  MaxLength,
  ValidateNested,
  IsEnum,
} from "class-validator";

import { Type } from "class-transformer";
import { RecipeIngredients } from "../../recipeIngredients/base/RecipeIngredients";
import { EnumRecipesRecipeType } from "./EnumRecipesRecipeType";

@ObjectType()
class Recipes {
  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  cookingTime!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isFavorite!: boolean | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: () => [RecipeIngredients],
  })
  @ValidateNested()
  @Type(() => RecipeIngredients)
  @IsOptional()
  recipeIngredientsItems?: Array<RecipeIngredients>;

  @ApiProperty({
    required: false,
    enum: EnumRecipesRecipeType,
  })
  @IsEnum(EnumRecipesRecipeType)
  @IsOptional()
  @Field(() => EnumRecipesRecipeType, {
    nullable: true,
  })
  recipeType?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  servings!: number | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Recipes as Recipes };
