/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested, IsEnum } from "class-validator";
import { StringFilter } from "../../util/StringFilter";
import { BooleanNullableFilter } from "../../util/BooleanNullableFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { RecipeIngredientsListRelationFilter } from "../../recipeIngredients/base/RecipeIngredientsListRelationFilter";
import { EnumRecipesRecipeType } from "./EnumRecipesRecipeType";

@InputType()
class RecipesWhereInput {
  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  cookingTime?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: BooleanNullableFilter,
  })
  @Type(() => BooleanNullableFilter)
  @IsOptional()
  @Field(() => BooleanNullableFilter, {
    nullable: true,
  })
  isFavorite?: BooleanNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => RecipeIngredientsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RecipeIngredientsListRelationFilter)
  @IsOptional()
  @Field(() => RecipeIngredientsListRelationFilter, {
    nullable: true,
  })
  recipeIngredientsItems?: RecipeIngredientsListRelationFilter;

  @ApiProperty({
    required: false,
    enum: EnumRecipesRecipeType,
  })
  @IsEnum(EnumRecipesRecipeType)
  @IsOptional()
  @Field(() => EnumRecipesRecipeType, {
    nullable: true,
  })
  recipeType?: "Option1";

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  servings?: IntNullableFilter;
}

export { RecipesWhereInput as RecipesWhereInput };
