/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { RecipeIngredientsService } from "../recipeIngredients.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { RecipeIngredientsCreateInput } from "./RecipeIngredientsCreateInput";
import { RecipeIngredients } from "./RecipeIngredients";
import { RecipeIngredientsFindManyArgs } from "./RecipeIngredientsFindManyArgs";
import { RecipeIngredientsWhereUniqueInput } from "./RecipeIngredientsWhereUniqueInput";
import { RecipeIngredientsUpdateInput } from "./RecipeIngredientsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class RecipeIngredientsControllerBase {
  constructor(
    protected readonly service: RecipeIngredientsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RecipeIngredients })
  @nestAccessControl.UseRoles({
    resource: "RecipeIngredients",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createRecipeIngredients(
    @common.Body() data: RecipeIngredientsCreateInput
  ): Promise<RecipeIngredients> {
    return await this.service.createRecipeIngredients({
      data: {
        ...data,

        ingredient: data.ingredient
          ? {
              connect: data.ingredient,
            }
          : undefined,

        recipe: data.recipe
          ? {
              connect: data.recipe,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        ingredient: {
          select: {
            id: true,
          },
        },

        quantity: true,

        recipe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [RecipeIngredients] })
  @ApiNestedQuery(RecipeIngredientsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "RecipeIngredients",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async recipeIngredientsItems(
    @common.Req() request: Request
  ): Promise<RecipeIngredients[]> {
    const args = plainToClass(RecipeIngredientsFindManyArgs, request.query);
    return this.service.recipeIngredientsItems({
      ...args,
      select: {
        createdAt: true,
        id: true,

        ingredient: {
          select: {
            id: true,
          },
        },

        quantity: true,

        recipe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RecipeIngredients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RecipeIngredients",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async recipeIngredients(
    @common.Param() params: RecipeIngredientsWhereUniqueInput
  ): Promise<RecipeIngredients | null> {
    const result = await this.service.recipeIngredients({
      where: params,
      select: {
        createdAt: true,
        id: true,

        ingredient: {
          select: {
            id: true,
          },
        },

        quantity: true,

        recipe: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RecipeIngredients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RecipeIngredients",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateRecipeIngredients(
    @common.Param() params: RecipeIngredientsWhereUniqueInput,
    @common.Body() data: RecipeIngredientsUpdateInput
  ): Promise<RecipeIngredients | null> {
    try {
      return await this.service.updateRecipeIngredients({
        where: params,
        data: {
          ...data,

          ingredient: data.ingredient
            ? {
                connect: data.ingredient,
              }
            : undefined,

          recipe: data.recipe
            ? {
                connect: data.recipe,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          ingredient: {
            select: {
              id: true,
            },
          },

          quantity: true,

          recipe: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RecipeIngredients })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "RecipeIngredients",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteRecipeIngredients(
    @common.Param() params: RecipeIngredientsWhereUniqueInput
  ): Promise<RecipeIngredients | null> {
    try {
      return await this.service.deleteRecipeIngredients({
        where: params,
        select: {
          createdAt: true,
          id: true,

          ingredient: {
            select: {
              id: true,
            },
          },

          quantity: true,

          recipe: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
