/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ShoppingCartService } from "../shoppingCart.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ShoppingCartCreateInput } from "./ShoppingCartCreateInput";
import { ShoppingCart } from "./ShoppingCart";
import { ShoppingCartFindManyArgs } from "./ShoppingCartFindManyArgs";
import { ShoppingCartWhereUniqueInput } from "./ShoppingCartWhereUniqueInput";
import { ShoppingCartUpdateInput } from "./ShoppingCartUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ShoppingCartControllerBase {
  constructor(
    protected readonly service: ShoppingCartService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ShoppingCart })
  @nestAccessControl.UseRoles({
    resource: "ShoppingCart",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createShoppingCart(
    @common.Body() data: ShoppingCartCreateInput
  ): Promise<ShoppingCart> {
    return await this.service.createShoppingCart({
      data: data,
      select: {
        createdAt: true,
        createdTime: true,
        id: true,
        ingredients: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ShoppingCart] })
  @ApiNestedQuery(ShoppingCartFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ShoppingCart",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async shoppingCarts(@common.Req() request: Request): Promise<ShoppingCart[]> {
    const args = plainToClass(ShoppingCartFindManyArgs, request.query);
    return this.service.shoppingCarts({
      ...args,
      select: {
        createdAt: true,
        createdTime: true,
        id: true,
        ingredients: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ShoppingCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ShoppingCart",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async shoppingCart(
    @common.Param() params: ShoppingCartWhereUniqueInput
  ): Promise<ShoppingCart | null> {
    const result = await this.service.shoppingCart({
      where: params,
      select: {
        createdAt: true,
        createdTime: true,
        id: true,
        ingredients: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ShoppingCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ShoppingCart",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateShoppingCart(
    @common.Param() params: ShoppingCartWhereUniqueInput,
    @common.Body() data: ShoppingCartUpdateInput
  ): Promise<ShoppingCart | null> {
    try {
      return await this.service.updateShoppingCart({
        where: params,
        data: data,
        select: {
          createdAt: true,
          createdTime: true,
          id: true,
          ingredients: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ShoppingCart })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ShoppingCart",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteShoppingCart(
    @common.Param() params: ShoppingCartWhereUniqueInput
  ): Promise<ShoppingCart | null> {
    try {
      return await this.service.deleteShoppingCart({
        where: params,
        select: {
          createdAt: true,
          createdTime: true,
          id: true,
          ingredients: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
