/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { FridgeItemsService } from "../fridgeItems.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { FridgeItemsCreateInput } from "./FridgeItemsCreateInput";
import { FridgeItems } from "./FridgeItems";
import { FridgeItemsFindManyArgs } from "./FridgeItemsFindManyArgs";
import { FridgeItemsWhereUniqueInput } from "./FridgeItemsWhereUniqueInput";
import { FridgeItemsUpdateInput } from "./FridgeItemsUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class FridgeItemsControllerBase {
  constructor(
    protected readonly service: FridgeItemsService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FridgeItems })
  @nestAccessControl.UseRoles({
    resource: "FridgeItems",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createFridgeItems(
    @common.Body() data: FridgeItemsCreateInput
  ): Promise<FridgeItems> {
    return await this.service.createFridgeItems({
      data: data,
      select: {
        createdAt: true,
        expirationDate: true,
        id: true,
        name: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [FridgeItems] })
  @ApiNestedQuery(FridgeItemsFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "FridgeItems",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async fridgeItemsItems(
    @common.Req() request: Request
  ): Promise<FridgeItems[]> {
    const args = plainToClass(FridgeItemsFindManyArgs, request.query);
    return this.service.fridgeItemsItems({
      ...args,
      select: {
        createdAt: true,
        expirationDate: true,
        id: true,
        name: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FridgeItems })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FridgeItems",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async fridgeItems(
    @common.Param() params: FridgeItemsWhereUniqueInput
  ): Promise<FridgeItems | null> {
    const result = await this.service.fridgeItems({
      where: params,
      select: {
        createdAt: true,
        expirationDate: true,
        id: true,
        name: true,
        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FridgeItems })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FridgeItems",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateFridgeItems(
    @common.Param() params: FridgeItemsWhereUniqueInput,
    @common.Body() data: FridgeItemsUpdateInput
  ): Promise<FridgeItems | null> {
    try {
      return await this.service.updateFridgeItems({
        where: params,
        data: data,
        select: {
          createdAt: true,
          expirationDate: true,
          id: true,
          name: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FridgeItems })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "FridgeItems",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteFridgeItems(
    @common.Param() params: FridgeItemsWhereUniqueInput
  ): Promise<FridgeItems | null> {
    try {
      return await this.service.deleteFridgeItems({
        where: params,
        select: {
          createdAt: true,
          expirationDate: true,
          id: true,
          name: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
